# Generated by Django 4.2.10 on 2025-06-13 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='product',
            name='use_cases',
        ),
    ]
