# Generated by Django 4.2.10 on 2025-06-13 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_product_benefits_remove_product_use_cases'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('from_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_products', to='core.product', verbose_name='Основной продукт')),
                ('to_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_products', to='core.product', verbose_name='Связанный продукт')),
            ],
            options={
                'verbose_name': 'Связанный продукт',
                'verbose_name_plural': 'Связанные продукты',
                'ordering': ['order'],
                'unique_together': {('from_product', 'to_product')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, through='core.RelatedProduct', to='core.product', verbose_name='Связанные продукты'),
        ),
    ]
