# Generated by Django 4.2.10 on 2025-06-14 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.JSONField(default=list, verbose_name='Возможности'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.JSONField(default=dict, verbose_name='Технические характеристики'),
        ),
    ]
